# fly.toml app configuration file generated for persona-backend on 2025-02-24T15:24:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'persona-backend'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/characters/ping'
    protocol = 'http'

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
